# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11dbaf5290514a422a754f3931f2f357bc091ec8e1957bab4bb9a6ea35886085a90c420a27a3f1b417dc231e7da913f76c75e4a83f8bc32571a338e8953bd849

test:
  secret_key_base: e9899dd2e856a628db79c07666bebaa107dcec59447ff146c859cf3a4f58a165ae10b4c3e30b76f6cf20813ba2ea254a8e6f9529c3be7a3a37507079f53920fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
